---
services:

  vocab:
    container_name: vocab-service
    build: .
    ports:
      - 8080:8080
    networks:
      - vonet
    env_file:
      - credentials.env

  redis:
    container_name: redisdb
    image: ghcr.io/aut-cloud-computing-fall-2024/redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - vonet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - vonet
    ports:
      - 9090:9090
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - vonet
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-storage:/var/lib/grafana

volumes:
  redis-data:
  grafana-storage:

networks:
  vonet:
    driver: bridge

...